site_name: sheldonhull
repo_url: https://github.com/sheldonhull/digital-garden

theme:
  name: material
  palette:
    scheme: slate
  icon:
    logo: material/security
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - tags
