---
#INHERIT: config/mkdocs.nav.yml
site_name: digital garden
repo_url: https://github.com/sheldonhull/digital-garden
use_directory_urls: true
docs_dir: notes
site_dir: .artifacts/_site
theme:
  name: material
  custom_dir: custom_theme/

  #logo: assets/icons/regular_expression_light.svg
  logo: assets/images/sheldon-avatar.jpg
  font:
    # text: Raleway
    code: Fira Code

  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    - toc.follow
    - navigation.top
    - navigation.path
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes
  - toc:
      permalink: 🔗
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      # line_spans: __span
      # pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # https://github.com/squidfunk/mkdocs-material/tree/master/material/.icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - awesome-pages:
      # filename: .index
      collapse_single_pages: true
      strict: false
      order: desc
      sort_type: natural
  # order_by: title # ERROR: runs into error with dates

  - blog:
      enabled: true
      draft_on_serve: true
      draft_if_future_date: true

      blog_dir: .
      post_dir: '{blog}/posts'
      # post_dir: '{blog}/posts'
      # post_url_date_format: yyyy/MM/dd
      post_url_format: '{slug}'
      blog_toc: true
      post_excerpt: optional
      post_slugify_separator: '-'
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

      categories: false
      archive: !ENV CI true
      archive_name: archive
      archive_date_format: yyyy
      archive_url_date_format: 'yyyy'
      archive_url_format: '{date}'
      archive_toc: true

  - autolinks
  - tags
    # tags_file: posts/tags.md
  #  - tags:
  #      enabled: !ENV [CI, false]
  - search
  - glightbox
  - rss:
      abstract_chars_count: 160 # -1 for full content
      abstract_delimiter: <!-- more -->
      categories:
        - tags
      comments_path: '#__comments'
      date_from_meta:
        as_creation: 'date'
        as_update: false
        datetime_format: '%Y-%m-%d %H:%M' #'%Y-%m-%d %H:%M'
        default_timezone: America/Chicago
        default_time: '09:30'
      enabled: false
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: '.*'
      url_parameters:
        utm_source: 'documentation'
        utm_medium: 'RSS'
        utm_campaign: 'feed-syndication'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true

# dev_addr: '0.0.0.0:8000' # since running dockerized, need to use 0.0.0.0 since 127.0.0.1 won't resolve to docker gateway
extra_css:
  - stylesheets/extra.css
  - stylesheets/gist.css
  - stylesheets/code-highlighting.css
extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
remote_branch: gh-pages
# nav:
#   - Blog:
#       - posts/index.md
watch:
  - config/
nav:
  - home: welcome.md
  - posts: index.md
  - notes:
      - ... | development/**
      - ... | career/**

        # - '/development/':
        #     - ai: development/ai/index.md
        #     - aws: development/aws/index.md
        #     - build-release-engineering: development/build-release-engineering/index.md
        #     - end: development/front-end/index.md
        #     - go: development/go/index.md
        #     - kubernetes: development/kubernetes/index.md
        #     - observability: development/observability/index.md
        #     - powershell: development/powershell/index.md
        #     - shell: development/shell/index.md
        #     - tooling: development/tooling/index.md
# nav:
#   - blog:
#       - posts/index.md
# - posts:
#     - posts/index.md
#     - ... | posts/**

# - notes:
#     - notes/index.md
#     - ... | development/**
#     - ... | career/**
#     - ... | technology/**

#   # - index.md
#   - posts:

#       # - posts/index.md
#       # - ... | blog/posts/**
#       # - ... | posts/**
#       # | blog/posts/**

#       # - blog/**/*.md
#       # - ... | notes/blog/posts/2023/**
#       # - ...
#       # - ... | notes/blog/posts/2022/**

#       # - welcome: index.md
#       # - posts:
#       #     - blog/index.md
#       #     # - ... | blog/posts/2023/**
#       #     # - archive:
#       #     # - ... | archive/**
