---
site_name: digital garden
repo_url: https://github.com/sheldonhull/digital-garden
use_directory_urls: true
theme:
  name: material
  logo: assets/icons/regular_expression_light.svg
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: 🔗
  - attr_list

plugins:
  - tags
  - search

dev_addr: '0.0.0.0:8000' # since running dockerized, need to use 0.0.0.0 since 127.0.0.1 won't resolve to docker gateway
extra_css:
  - stylesheets/extra.css
  - stylesheets/gist.css
  - stylesheets/code-highlighting.css
custom_dir: overrides
