---
name: trunk-cache
on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions: read-all

jobs:
  cache:
    name: Cache Trunk
    runs-on: ub#untu-latest
    timeout-minutes: 10
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: populate_cache_only
