---
name: mkdocs-publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      changes: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'notes/**/*.md'
              - 'mkdocs.yml'
              - '.github/workflows/mkdocs-publish.yml'
      - if: steps.changes.outputs.src == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - if: steps.changes.outputs.src == 'true'
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - if: steps.changes.outputs.src == 'true'
        run: pip install mkdocs-material mkdocs-glightbox
      # - run: mkdocs gh-deploy --force
      - if: steps.changes.outputs.src == 'true'
        name: mkdocs-build #(_site directory name is used for Jekyll compatiblity)
        run: mkdocs build --config-file ./mkdocs.yml --site-dir ./_site
      - if: steps.changes.outputs.src == 'true'
        name: upload-pages-artifact
        uses: actions/upload-pages-artifact@253fd476ed429e83b7aae64a92a75b4ceb1a17cf # renovate: tag=v1.0.7
  # Deployment job
  deploy:
    needs: build
    if: ${{ needs.build.outputs.changes == 'true' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: deploy-to-github-pages
        id: deployment
        uses: actions/deploy-pages@v1
