---
name: mkdocs-publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      changes: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'notes/**/*.md'
              - 'mkdocs.yml'
              - '.github/workflows/mkdocs-publish.yml'
      - if: steps.changes.outputs.src == 'true'
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4
        with:
          python-version: 3.x
      - if: steps.changes.outputs.src == 'true'
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - if: steps.changes.outputs.src == 'true'
        run: pip install mkdocs-material mkdocs-glightbox mkdocs-rss-plugin
      # - run: mkdocs gh-deploy --force
      - if: steps.changes.outputs.src == 'true'
        name: mkdocs-build #(_site directory name is used for Jekyll compatiblity)
        run: mkdocs build --config-file ./mkdocs.yml --site-dir ./_site
      - if: steps.changes.outputs.src == 'true'
        name: upload-pages-artifact
        uses: actions/upload-pages-artifact@66b63f4a7de003f4f00cc8e9af4b83b8f2abdb96 # v1.0.9
  # Deployment job
  deploy:
    needs: build
    if: ${{ needs.build.outputs.changes == 'true' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: deploy-to-github-pages
        id: deployment
        uses: actions/deploy-pages@ee48c7b82e077d7b8ef30b50a719e6a792a50c9a # v2
