---
name: trunk-check

on:
  pull_request:
    branches:
      - main
jobs:
  trunk-check:
    name: check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          working_directory: foo
          aqua_opts: '--tags lint'
          aqua_version: v2.8.0
        env:
          AQUA_CONFIG: aqua-config.yaml
          AQUA_LOG_LEVEL: debug
      - name: Trunk Check
        uses: trunk-io/trunk-action@e5f1a3f123a2440f9cd28e036495a1c1f2a20568 # v1
