---
name: trunk-check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trunk-check:
    name: check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: aquaproj/aqua-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        with:
          # working_directory: foo
          aqua_opts: '--tags lint'
          aqua_version: v2.10.1
        env:
          AQUA_LOG_LEVEL: debug
      - name: Trunk Check
        uses: trunk-io/trunk-action@883e222ef19201ad402ef73e58101ec8186d7d54 # v1
